done

diff --git a/setup-env/action.yaml b/setup-env/action.yaml
--- a/setup-env/action.yaml
+++ b/setup-env/action.yaml
@@ -82,6 +82,24 @@ runs:
       uses: actions/setup-node@v3
       with:
         node-version-file: ${{ env.NODE_VERSION_FILE }}
+      continue-on-error: true
+
+    - name: Check for node installation
+      if: env.PACKAGE_MANAGER && env.NODE_VERSION_FILE
+      shell: bash
+      run: |
+        if ! command -v node >/dev/null; then
+          echo "::warning::Failed to install specified node version - installing latest node instead."
+          cat >>$GITHUB_ENV <<EOF
+        FAILED_NODE_INSTALL=true
+        EOF
+        fi
+
+    - name: Install backup node version
+      if: env.PACKAGE_MANAGER && env.NODE_VERSION_FILE && env.FAILED_NODE_INSTALL == 'true'
+      uses: actions/setup-node@v3
+      with:
+        node-version-file: latest
 
     - name: Cache node_modules
       if: inputs.cache-key && env.PACKAGE_MANAGER
