revert that

diff --git a/setup-env/action.yaml b/setup-env/action.yaml
--- a/setup-env/action.yaml
+++ b/setup-env/action.yaml
@@ -88,10 +88,12 @@ runs:
       if: env.PACKAGE_MANAGER && env.NODE_VERSION_FILE
       shell: bash
       run: |
-        echo "::warning::Failed to install specified node version - installing latest node instead."
-        cat >>$GITHUB_ENV <<EOF
+        if ! command -v node >/dev/null; then
+          echo "::warning::Failed to install specified node version - installing latest node instead."
+          cat >>$GITHUB_ENV <<EOF
         FAILED_NODE_INSTALL=true
         EOF
+        fi
 
     - name: Install backup node version
       if: env.PACKAGE_MANAGER && env.NODE_VERSION_FILE && env.FAILED_NODE_INSTALL == 'true'
