fix: install latest node correctly (#189)
Fixes a typo in the backup path. Additionally, now always installs the
latest node if the first node fails, so that that code path gets tested.

diff --git a/.github/workflows/docker_repo_tests.yaml b/.github/workflows/docker_repo_tests.yaml
--- a/.github/workflows/docker_repo_tests.yaml
+++ b/.github/workflows/docker_repo_tests.yaml
@@ -32,6 +32,7 @@ jobs:
               # terrascan scans dockerfile.js (a JS file for parsing dockerfiles) as a dockerfile itself
               echo "src/languages/dockerfile.js" >> .gitignore
               cp local-action/repo_tests/highlightjs.yaml .trunk/user.yaml
+            cache: true
 
           - repo: pallets/flask
             ref: 4bcd4be6b7d69521115ef695a379361732bcaea6
@@ -39,22 +40,44 @@ jobs:
               # prettier chokes on this malformed html file
               echo "examples/celery/src/task_app/templates/index.html" >> .gitignore
               cp local-action/repo_tests/flask.yaml .trunk/user.yaml
+            cache: true
 
           - repo: postcss/postcss
             ref: aa9e03ea4708909631eba70500c8c0cc0708bb4e
             description: (uses pnpm)
             post-init: |
               ${TRUNK_PATH} check enable eslint
+            cache: true
 
           - repo: postcss/postcss
             ref: aa9e03ea4708909631eba70500c8c0cc0708bb4e
             description: (compat test for cli 1.0.0)
             post-init: |
               ${TRUNK_PATH} check enable eslint
+            cache: true
+
+          - repo: prawn-test-staging-rw/setup-node-test
+            ref: main
+            post-init: |
+              if [ "${FAILED_NODE_INSTALL}" != "true" ]; then
+                echo "::error::Initial setup node didn't fail"
+                exit 1
+              fi
+              if [ "${INSTALL_LATEST_NODE}" != "true" ]; then
+                echo "::error::Initial setup node didn't fail"
+                exit 1
+              fi
+            description: (test for setup-node)
+            pre-init: |
+              while which node > /dev/null; do
+                rm $(which node)
+              done
+            cache: false
 
           - repo: sass/sass
             ref: 225e176115211387e014d97ae0076d94de3152a1
             description: (uses npm)
+            cache: true
 
     steps:
       - name: Checkout ${{ matrix.repo }}
@@ -68,11 +91,15 @@ jobs:
         with:
           path: local-action
 
+      - name: Run pre-init
+        shell: bash
+        run: ${{ matrix.pre-init }}
+
       - name: Run trunk-action in ${{ matrix.repo }}
         id: trunk
         uses: ./local-action/
         with:
-          cache: true
+          cache: ${{ matrix.cache }}
           check-mode: all
           post-init: ${{ matrix.post-init }}
           arguments: --output-file=/tmp/landing-state.json
