feat: continue on node package install failure (#236)
### Problem

Currently, most of our check-on-prs/check nightly failures occur while
installing node packages, for a variety of reasons. Right now, this
causes the check to fail, and we report that "something went wrong".
Instead, we may want to disable linters that depend on node-modules
(specifically, stylelint and eslint) and lint the remaining files to
report our best-effort results.

Pros:
- We would report some issues, and some issues is better than no issues
- We wouldn't be erroring with a message that seems like an internal
error (because for all we know right now, it could be)

Cons:
- A user could introduce a lint issue in the same PR as a breaking
change to package.json and we would pass that PR
- I am pretty sure that we don't have a great way of surfacing to the
user that we're disabling eslint without writing an annoying amount of
boilerplate to send the data through the cli through services back to
github
  - We do log this in the action logs, but that's the most visible place

### Solution

After talking with Sam about this, we figured the best solution is to
disable the linters if we are auto-initing for the user, but not if the
user has a trunk.yaml and therefore has deliberately opted to see ts/js
issues.

### Testing

Added a repo test for
[prawn-test-staging-rw/node-packages-failure-test](https://github.com/prawn-test-staging-rw/node-packages-failure-test/tree/main)
that has an invalid package.json, and checks to make sure the action
disables eslint and stylelint, and continues after the failure.

diff --git a/.github/workflows/repo_tests.yaml b/.github/workflows/repo_tests.yaml
--- a/.github/workflows/repo_tests.yaml
+++ b/.github/workflows/repo_tests.yaml
@@ -35,7 +35,8 @@ jobs:
             description: (compile-commands.json)
             post-init: |
               # black complains about py2 code
-              ${TRUNK_PATH} check disable black
+              # markdownlint fails for some reason, and what we really care about anyways is clang-tidy
+              ${TRUNK_PATH} check disable black markdownlint
               mkdir build
               cd build
               cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
@@ -44,8 +45,6 @@ jobs:
               sed -i "s|lint:|lint:\n  compile_commands: json|" .trunk/trunk.yaml
               cp local-action/repo_tests/yaml_cpp.yaml .trunk/user.yaml
               ${TRUNK_PATH} check enable clang-tidy
-              # markdownlint fails for some reason, and what we really care about anyways is clang-tidy
-              ${TRUNK_PATH} check disable markdownlint
 
           - repo: pallets/flask
             ref: 4bcd4be6b7d69521115ef695a379361732bcaea6
@@ -75,6 +74,23 @@ jobs:
               fi
             description: (test for setup-node)
 
+          - repo: prawn-test-staging-rw/node-packages-failure-test
+            ref: main
+            post-init: |
+              if [ "${FAILED_NODE_PACKAGE_INSTALL}" != "true" ]; then
+                echo "::error::Node package install didn't fail"
+                exit 1
+              fi
+              if grep -q "✔ eslint" <(${TRUNK_PATH} check list --color=false); then
+                echo "::error::eslint not disabled"
+                exit 1
+              fi
+              if grep -q "✔ stylelint" <(${TRUNK_PATH} check list --color=false); then
+                echo "::error::stylelint not disabled"
+                exit 1
+              fi
+            description: (test for continuing on node package install failure)
+
           - repo: replayio/devtools
             ref: 730a9f0ddaafefc2a1a293d6924ce3910cd156ac
             description: (has trunk.yaml)
@@ -95,10 +111,7 @@ jobs:
             description: (has trunk.yaml)
             post-init: |
               # all of these linters have failures
-              ${TRUNK_PATH} check disable svgo
-              ${TRUNK_PATH} check disable golangci-lint
-              ${TRUNK_PATH} check disable prettier
-              ${TRUNK_PATH} check disable oxipng
+              ${TRUNK_PATH} check disable svgo golangci-lint prettier oxipng
 
           - repo: shopify/draggable
             ref: e6cf325a98c11b8aefbfb626b7a91b95d1c340c9
